# Generated by Django 6.0.3 on 2026-03-30 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='end_time',
        ),
        migrations.AddField(
            model_name='lot',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания торгов'),
        ),
    ]
