# Generated by Django 6.0.3 on 2026-03-30 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Ставка', 'verbose_name_plural': 'Ставки'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctions.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lots/%Y/%m/%d/', verbose_name='Изображение лота'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название лота'),
        ),
    ]
